# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev-hello-world',
                'doc_host': 'https://fastai.github.io',
                'git_url': 'https://github.com/fastai/nbdev-hello-world',
                'lib_path': 'nbdev_hello_world'},
  'syms': { 'nbdev_hello_world.core': { 'nbdev_hello_world.core.foo': ('core.html#foo', 'nbdev_hello_world/core.py'),
                                        'nbdev_hello_world.core.foo_core_mixin': ( 'core_mixin.html#foo_core_mixin',
                                                                                   'nbdev_hello_world/core.py')},
            'nbdev_hello_world.four': { 'nbdev_hello_world.four.fortytwo': ( 'four/nested_in_folder.html#fortytwo',
                                                                             'nbdev_hello_world/four.py')},
            'nbdev_hello_world.three.four': { 'nbdev_hello_world.three.four.fortytwo': ( 'four/nested_in_folder.html#fortytwo',
                                                                                         'nbdev_hello_world/three/four.py')},
            'nbdev_hello_world.three.handahalf': { 'nbdev_hello_world.three.handahalf.nakedgun': ( 'nested.html#nakedgun',
                                                                                                   'nbdev_hello_world/three/handahalf.py')},
            'nbdev_hello_world.two': {'nbdev_hello_world.two.foo_two': ('core_mixin.html#foo_two', 'nbdev_hello_world/two.py')}}}
