# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['foo', 'foo_core_mixin']

# %% ../nbs/00_core.ipynb 3
def foo(): pass

# %% ../nbs/01_core_mixin.ipynb 3
def foo_core_mixin(): # will get exported to core
    pass