# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/four/04_nested_in_folder.ipynb.

# %% auto 0
__all__ = ['fortytwo']

# %% ../../nbs/four/04_nested_in_folder.ipynb 2
def fortytwo():
    return "I'm a naked gun"
